name: Docker Images CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ekaymoldaev/GitHub_Actions:${{github.sha }}
        
      - name: Docker Push
        run: docker push ekaymoldaev/GitHub_Actions:${{github.sha }}


